# Generated by Django 3.2.7 on 2021-10-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_Extract', '0004_orderitem_product_realuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealUser',
        ),
    ]
