# Generated by Django 3.2.7 on 2021-10-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_Extract', '0008_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['membership']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
